inherit_from: .rubocop_todo.yml

AllCops:
  Include:
  - Gemfile
  - '**/Rakefile'
  - resque-scheduler.gemspec
  - bin/resque-scheduler
#  TargetRubyVersion: 2.3

Bundler/DuplicatedGem:
  Enabled: false

Documentation:
  Enabled: false

Security/MarshalLoad:
  Exclude:
    - 'test/multi_process_test.rb'
Security/YAMLLoad:
  Exclude:
    - 'examples/config/initializers/resque-web.rb'
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 110
