inherit_from: .rubocop_todo.yml

AllCops:
  Include:
  - Gemfile
  - '**/Rakefile'
  - resque-scheduler.gemspec
  - bin/resque-scheduler
#  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 110
