inherit_from: .rubocop_todo.yml

#AllCops:
#  TargetRubyVersion: 2.3

Bundler/DuplicatedGem:
  Enabled: false

Documentation:
  Enabled: false

Lint/UnusedBlockArgument:
  Exclude:
    - 'examples/dynamic-scheduling/lib/tasks/resque.rake'

Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 110

Naming/HeredocDelimiterNaming:
  Enabled: false

Security/MarshalLoad:
  Exclude:
    - 'test/multi_process_test.rb'
Security/YAMLLoad:
  Exclude:
    - 'examples/config/initializers/resque-web.rb'

Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'
