name: Rubocop

on:
  push:
  pull_request:
    branches: [master]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Ruby linter
        run: bundle exec rubocop
