name: CI

on:
  push:
  pull_request:

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        redis-version:
          - "4.0"
          - 4.1
          - 4.2
          - 4.3
          - 4.4
          - 4.5
          - 4.6
          - 4.7
          - 4.8
          - latest
        ruby-version:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - "3.0"
          - 3.1
        resque-version:
          - "master"
          - "~> 2.2.0"
          - "~> 1.27"
        rufus-scheduler:
          - "3.6"
        exclude:
          - ruby-version: head
            rufus-scheduler: 3.2

          - ruby-version: 2.3
            resque-version: 1.27
            rufus-scheduler: 3.4
          - ruby-version: 2.3
            resque-version: 1.27
            rufus-scheduler: 3.5
          - ruby-version: 2.5
            resque-version: 2.2.0
            rufus-scheduler: 3.5
          - ruby-version: 2.5
            resque-version: master
            rufus-scheduler: 3.2
    env:
      REDIS_VERSION: "${{ matrix.redis-version }}"
      RESQUE: "${{ matrix.resque-version }}"
      RUFUS_SCHEDULER: "${{ matrix.rufus-scheduler }}"
      COVERAGE: 1

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: sudo apt-get install redis-server
      - run: bundle exec rake
      - run: bin/bundle_console_test.sh
